### PR TITLE
Make compilation more flexible

### PR DESCRIPTION
**Pull request by rmcbc**
Make compilation more flexible allowing to define in custom.h your own variation to devices and define four WiFi networks.

The only change in hardware.h is:

#if not defined(MANUFACTURER)

    // -----------------------------------------------------------------------------
    // ESPurna Core
    // -----------------------------------------------------------------------------

...

#endif

// -----------------------------------------------------------------------------
// Check definitions
// -----------------------------------------------------------------------------

...

### CODE REVIEW

**Comment by mcspr** [comment]
https://github.com/xoseperez/espurna/blob/900bcb8bf17f268e4df1cbcf6cff34dede02a361/code/espurna/config/hardware.h#L3857

Why not just define MANUFACTURER and DEVICE and have the same ifdef(MY_DEVICE) in custom header? Or do you mean to override some existing define, that's why we need to remove checks in hardware.h?

**Comment by rmcbc** [comment]
In my custom.h I want to override the original definition in hardware.h, example:

    #elif defined(ALLTERCO_SHELLY1)

        // Info
        #define MANUFACTURER        "ALLTERCO"
        #define DEVICE              "SHELLY1"

        // Buttons
        #define BUTTON1_PIN         5
        //#define BUTTON1_MODE        BUTTON_SWITCH
        #define BUTTON1_MODE        BUTTON_PUSHBUTTON // | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON1_RELAY       1

        #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON1_CLICK       BUTTON_MODE_NONE
        #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

        // Relays
        #define RELAY1_PIN          4
        #define RELAY1_TYPE         RELAY_TYPE_NORMAL

        // Non-core modules
        #define ALEXA_SUPPORT               1
        #define DOMOTICZ_SUPPORT            1
        #define HOMEASSISTANT_SUPPORT       1
        #define I2C_SUPPORT                 0
        #define SCHEDULER_SUPPORT           1
        #define SENSOR_SUPPORT              0
        #define THINGSPEAK_SUPPORT          0
#endif

**Comment by rmcbc** [comment]
This way I can define my base configurations and the specific definition for the existing devices, also I can define many configurations for the same device.
And because I have 4 WiFi routers I can add all of them to the same device definition using a free IP address for all new devices 192.168.1.9 then using web interface I configure the one that I want and the name of it.
It's easier when you have 70 devices to install and configure.
I don't need to change any line in the original code.

My custom.h:

// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
//                                 defaults.h
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// General
// -----------------------------------------------------------------------------

// Default hostname will be ESPURNA-XXXXXX, where XXXXXX is last 3 octets of chipID
#define HOSTNAME                "SonoffBasic09"

// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
//                                  general.h
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// HEARTBEAT
//------------------------------------------------------------------------------

#define HEARTBEAT_INTERVAL          900000    // 15 min. // Interval between heartbeat messages (in ms)

// Values that will be reported in heartbeat
#define HEARTBEAT_REPORT_STATUS     1
#define HEARTBEAT_REPORT_SSID       0
#define HEARTBEAT_REPORT_IP         0
#define HEARTBEAT_REPORT_MAC        0
#define HEARTBEAT_REPORT_RSSI       0
#define HEARTBEAT_REPORT_UPTIME     0
#define HEARTBEAT_REPORT_DATETIME   0
#define HEARTBEAT_REPORT_FREEHEAP   0
#define HEARTBEAT_REPORT_VCC        0
#define HEARTBEAT_REPORT_RELAY      1
#define HEARTBEAT_REPORT_LIGHT      0
#define HEARTBEAT_REPORT_HOSTNAME   0
#define HEARTBEAT_REPORT_DESCRIPTION 0
#define HEARTBEAT_REPORT_APP        0
#define HEARTBEAT_REPORT_VERSION    0
#define HEARTBEAT_REPORT_BOARD      0
#define HEARTBEAT_REPORT_LOADAVG    0
#define HEARTBEAT_REPORT_INTERVAL   0

// -----------------------------------------------------------------------------
// WEBSOCKETS
// -----------------------------------------------------------------------------

// This will only be enabled if WEB_SUPPORT is 1 (this is the default value)
#define WS_AUTHENTICATION           0           // WS authentication ON by default (see #507)

// -----------------------------------------------------------------------------
// ALEXA
// -----------------------------------------------------------------------------

// This setting defines whether Alexa support should be built into the firmware
#define ALEXA_SUPPORT               1               // Enable Alexa support by default (10.84Kb)

// This is default value for the alexaEnabled setting that defines whether
// this device should be discoberable and respond to Alexa commands.
// Both ALEXA_SUPPORT and alexaEnabled should be 1 for Alexa support to work.
#define ALEXA_ENABLED               0

//------------------------------------------------------------------------------
// GENERAL
//------------------------------------------------------------------------------

#define USE_PASSWORD            0               // Insecurity caution! Disabling this will disable password querying completely.

//------------------------------------------------------------------------------
// BUTTON
//------------------------------------------------------------------------------

#define BUTTON_DBLCLICK_DELAY       10000       // Time in ms to wait for a second (or third...) click
#define BUTTON_LNGCLICK_DELAY       11000       // Time in ms holding the button down to get a long click
#define BUTTON_LNGLNGCLICK_DELAY    12000       // Time in ms holding the button down to get a long-long click

//------------------------------------------------------------------------------
// RELAY
//------------------------------------------------------------------------------

#define RELAY_BOOT_MODE             RELAY_BOOT_SAME
#define RELAY_SYNC                  RELAY_SYNC_NONE_OR_ONE
#define RELAY_PULSE_MODE            RELAY_PULSE_NONE
#define RELAY_PULSE_TIME            0

//------------------------------------------------------------------------------
// WIFI
//------------------------------------------------------------------------------

#define WIFI_FALLBACK_APMODE        0

#define WIFI1_SSID                  "WIFI2"
#define WIFI1_PASS                  "WifiPassword"
#define WIFI1_IP                    "192.168.1.9"
#define WIFI1_GW                    "192.168.1.1"
#define WIFI1_MASK                  "255.255.255.0"
#define WIFI1_DNS                   "192.168.1.1"

#define WIFI2_SSID                  "WIFI1"
#define WIFI2_PASS                  "WifiPassword"
#define WIFI2_IP                    "192.168.1.9"
#define WIFI2_GW                    "192.168.1.1"
#define WIFI2_MASK                  "255.255.255.0"
#define WIFI2_DNS                   "192.168.1.1"

#define WIFI3_SSID                  "WIFI0"
#define WIFI3_PASS                  "WifiPassword"
#define WIFI3_IP                    "192.168.1.9"
#define WIFI3_GW                    "192.168.1.1"
#define WIFI3_MASK                  "255.255.255.0"
#define WIFI3_DNS                   "192.168.1.1"

#define WIFI4_SSID                  "WIFI3"
#define WIFI4_PASS                  "WifiPassword"
#define WIFI4_IP                    "192.168.1.9"
#define WIFI4_GW                    "192.168.1.1"
#define WIFI4_MASK                  "255.255.255.0"
#define WIFI4_DNS                   "192.168.1.1"

// -----------------------------------------------------------------------------
// WEB
// -----------------------------------------------------------------------------

#define WEB_FORCE_PASS_CHANGE       0           // Force the user to change the password if default one

// -----------------------------------------------------------------------------
// MQTT
// -----------------------------------------------------------------------------

#define MQTT_SUPPORT                1                       // MQTT support (22.38Kb async, 12.48Kb sync)


#define MQTT_ENABLED                1                       // Do not enable MQTT connection by default

#define MQTT_SERVER                 "192.168.1.220"         // Default MQTT broker address
#define MQTT_USER                   "mosquitto"             // Default MQTT broker usename
#define MQTT_PASS                   ""                      // Default MQTT broker password
#define MQTT_PORT                   1883                    // MQTT broker port
#define MQTT_TOPIC                  "espurna/{hostname}"    // Default MQTT base topic

// -----------------------------------------------------------------------------
// NTP
// -----------------------------------------------------------------------------

#define NTP_TIME_OFFSET             0           // Default timezone offset (GMT+0)

// -----------------------------------------------------------------------------
// API
// -----------------------------------------------------------------------------

#define API_SUPPORT                 1           // API (REST & RPC) support built in

// This will only be enabled if WEB_SUPPORT is 1 (this is the default value)
#define API_ENABLED                 0           // Do not enable API by default

#define API_RESTFUL                 0           // A restful API requires changes to be issued as PUT requests
                                                // Setting this to 0 will allow using GET to change relays, for instance

// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
//                                  hardware.h
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Configuration HELP
// -----------------------------------------------------------------------------
//
// MANUFACTURER: Name of the manufacturer of the board ("string")
// DEVICE: Name of the device ("string")
// BUTTON#_PIN: GPIO for the n-th button (1-based, up to 4 buttons)
// BUTTON#_RELAY: Relay number that will be bind to the n-th button (1-based)
// BUTTON#_MODE: A mask of options (BUTTON_PUSHBUTTON and BUTTON_SWITCH cannot be together)
//   - BUTTON_PUSHBUTTON: button event is fired when released
//   - BUTTON_SWITCH: button event is fired when pressed or released
//   - BUTTON_DEFAULT_HIGH: there is a pull up in place
//   - BUTTON_SET_PULLUP: set pullup by software
// RELAY#_PIN: GPIO for the n-th relay (1-based, up to 8 relays)
// RELAY#_TYPE: Relay can be RELAY_TYPE_NORMAL, RELAY_TYPE_INVERSE, RELAY_TYPE_LATCHED or RELAY_TYPE_LATCHED_INVERSE
// LED#_PIN: GPIO for the n-th LED (1-based, up to 8 LEDs)
// LED#_PIN_INVERSE: LED has inversed logic (lit when pulled down)
// LED#_MODE: Check types.h for LED_MODE_%
// LED#_RELAY: Linked relay (1-based)
//
// Besides, other hardware specific information should be stated here

// -----------------------------------------------------------------------------
// Itead Studio boards
// -----------------------------------------------------------------------------

#if defined(ITEAD_SONOFF_BASIC)

    // Info
    #define MANUFACTURER        "ITEAD"
    #define DEVICE              "SONOFF_BASIC"

    // Buttons
    #define BUTTON1_PIN         0
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON1_RELAY       1
    #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON1_CLICK       BUTTON_MODE_NONE
    #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE   


    #define EXTERNAL_BUTTON_TYPE    4   // -1 - No external switch or button
                                        //  0 - External switch (RX)
                                        //  1 - Button contact (RX) normaly open (When button pressed all events are available PRESS, CLICK, DBLCLICK, ...)
                                        //  2 - Button contact (RX) normaly open (When button pressed only PRESS event)
                                        //  3 - Button contact (RX) normaly closed (When button pressed only PRESS event)
                                        //  4 - Button contact (TX) normaly open (When button pressed only PRESS event)

    #if EXTERNAL_BUTTON_TYPE == 0

        // External switch (type 0)
        #define BUTTON2_PIN         3 // RX 
        #define BUTTON2_MODE        BUTTON_SWITCH | BUTTON_SET_PULLUP | BUTTON_DEFAULT_HIGH
        #define BUTTON2_RELAY       1

    #endif

    #if EXTERNAL_BUTTON_TYPE == 1

        // External press button (type 1)
        // Button contact normaly open (When button pressed all events are available PRESS, CLICK, DBLCLICK, ...)
        #define BUTTON2_PIN         3 // RX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_NONE
        #define BUTTON2_CLICK       BUTTON_MODE_TOGGLE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_TOGGLE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_TOGGLE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_TOGGLE

    #endif

    #if EXTERNAL_BUTTON_TYPE == 2

        // External press button (type 2)
        // Button contact normaly open (When button pressed only PRESS event)
        #define BUTTON2_PIN         3 // RX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #endif

    #if EXTERNAL_BUTTON_TYPE == 3

        // External press button (type 3)
        // Button contact normaly closed (When button pressed only PRESS event)
        #define BUTTON2_PIN         3 // RX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_SET_PULLUP
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #endif

    #if EXTERNAL_BUTTON_TYPE == 4

        // External press button (type 4)
        // Button contact normaly open (When button pressed only PRESS event)
        #define BUTTON2_PIN         1 // TX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #endif

    // Relays
    #define RELAY1_PIN          12
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL

    // LEDs
    #define LED1_PIN            13
    #define LED1_PIN_INVERSE    1

    // Non-core modules
    #define ALEXA_SUPPORT               1
    #define DOMOTICZ_SUPPORT            1
    #define HOMEASSISTANT_SUPPORT       1
    #define I2C_SUPPORT                 0
    #define SCHEDULER_SUPPORT           1
    #define SENSOR_SUPPORT              0
    #define THINGSPEAK_SUPPORT          0

#elif defined(ITEAD_SONOFF_DUAL_R2)

    #define MANUFACTURER        "ITEAD"
    #define DEVICE              "SONOFF_DUAL_R2"

    // Buttons
    #define BUTTON1_PIN         3       // Button RX on header
    //#define BUTTON1_PIN       0       // Button 0 on header
    #define BUTTON2_PIN         9       // Button 1 on header
    #define BUTTON3_PIN         10      // Physical button
    #define BUTTON1_RELAY       1
    #define BUTTON2_RELAY       2
    #define BUTTON3_RELAY       1
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON3_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH

    #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON1_CLICK       BUTTON_MODE_NONE
    #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

    #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON2_CLICK       BUTTON_MODE_NONE
    #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON1_CLICK       BUTTON_MODE_NONE
    #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE  

    // Relays
    #define RELAY1_PIN          12
    #define RELAY2_PIN          5
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL
    #define RELAY2_TYPE         RELAY_TYPE_NORMAL

    // LEDs
    #define LED1_PIN            13
    #define LED1_PIN_INVERSE    1

    // Non-core modules
    #define ALEXA_SUPPORT               1
    #define DOMOTICZ_SUPPORT            1
    #define HOMEASSISTANT_SUPPORT       1
    #define I2C_SUPPORT                 0
    #define SCHEDULER_SUPPORT           1
    #define SENSOR_SUPPORT              0
    #define THINGSPEAK_SUPPORT          0

 #elif defined(ITEAD_SONOFF_4CH)

        // Info
        #define MANUFACTURER        "ITEAD"
        #define DEVICE              "SONOFF_4CH"

        // Buttons
        #define BUTTON1_PIN         0
        #define BUTTON2_PIN         9
        #define BUTTON3_PIN         10
        #define BUTTON4_PIN         14

        #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON3_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON4_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH

        #define BUTTON1_RELAY       1
        #define BUTTON2_RELAY       2
        #define BUTTON3_RELAY       3       
        #define BUTTON4_RELAY       4

        #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON1_CLICK       BUTTON_MODE_NONE
        #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON3_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON3_CLICK       BUTTON_MODE_NONE
        #define BUTTON3_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON3_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON3_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON4_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON4_CLICK       BUTTON_MODE_NONE
        #define BUTTON4_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON4_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON4_LNGLNGCLICK BUTTON_MODE_NONE

        // Relays
        #define RELAY1_PIN          12
        #define RELAY2_PIN          5
        #define RELAY3_PIN          4
        #define RELAY4_PIN          15

        #define RELAY1_TYPE         RELAY_TYPE_NORMAL
        #define RELAY2_TYPE         RELAY_TYPE_NORMAL
        #define RELAY3_TYPE         RELAY_TYPE_NORMAL
        #define RELAY4_TYPE         RELAY_TYPE_NORMAL

        // LEDs
        #define LED1_PIN            13
        #define LED1_PIN_INVERSE    1

        // Non-core modules
        #define ALEXA_SUPPORT               1
        #define DOMOTICZ_SUPPORT            1
        #define HOMEASSISTANT_SUPPORT       1
        #define I2C_SUPPORT                 0
        #define SCHEDULER_SUPPORT           1
        #define SENSOR_SUPPORT              0
        #define THINGSPEAK_SUPPORT          0

        #define BUTTON5_PIN         3       // Button RX on header
        #define BUTTON6_PIN         2       // IO2

        #define BUTTON5_RELAY       3       
        #define BUTTON6_RELAY       4

        #define BUTTON5_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON6_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP

        #define BUTTON5_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON5_CLICK       BUTTON_MODE_NONE
        #define BUTTON5_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON5_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON5_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON6_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON6_CLICK       BUTTON_MODE_NONE
        #define BUTTON6_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON6_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON6_LNGLNGCLICK BUTTON_MODE_NONE

    #elif defined(ALLTERCO_SHELLY1)

        // Info
        #define MANUFACTURER        "ALLTERCO"
        #define DEVICE              "SHELLY1"

        // Buttons
        #define BUTTON1_PIN         5
        //#define BUTTON1_MODE        BUTTON_SWITCH
        #define BUTTON1_MODE        BUTTON_PUSHBUTTON // | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON1_RELAY       1

        #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON1_CLICK       BUTTON_MODE_NONE
        #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

        // Relays
        #define RELAY1_PIN          4
        #define RELAY1_TYPE         RELAY_TYPE_NORMAL

        // Non-core modules
        #define ALEXA_SUPPORT               1
        #define DOMOTICZ_SUPPORT            1
        #define HOMEASSISTANT_SUPPORT       1
        #define I2C_SUPPORT                 0
        #define SCHEDULER_SUPPORT           1
        #define SENSOR_SUPPORT              0
        #define THINGSPEAK_SUPPORT          0

#endif

**Comment by mcspr** [comment]
So maybe do this?
```
#if defined(MANUFACTURER) and defined(DEVICE)
// user has defined custom hardware, no need to check anything else
#elif defined(ESPURNA_CORE)
...etc.
#else 
#error "UNSUPPORTED HARDWARE!!"
#endif
```
Instead of hiding profiles, just add the check at the beginning
Since the hardware definition is a full copy anyways, that's why I was asking the reasoning behind not naming hardware define something different and avoiding this problem altogether.

Additional WiFi is ok (but I hope we some time figure out a way to store / apply that more clearly)

**Comment by rmcbc** [comment]
@mcspr I follow you suggestion it's cleaner, thanks.

**Comment by mcspr** [comment]
Thanks! I'll merge things in the morning

**Comment by rmcbc** [comment]
Thanks @mcspr

**Pull request merged**
