### PR TITLE
add support for JINVOO VALVE SM-AW713

### PR DESCRIPTION
**Pull request by reaper7**
jinvoo-valve-sm-aw713

### CODE REVIEW

**Comment by reaper7** [comment]
Type: Other
Board: Jinvoo SM-AW713
Build flag: JINVOO_VALVE_SM_AW713
Description: motorized valve

**Comment by mcspr** [comment]
Thanks!

Can you please also add platformio.ini entries for the .bin releases?
And I think it can also go into the readme here? https://github.com/xoseperez/espurna#embedded-switches (with images/devices/..pic..)

**Comment by reaper7** [comment]
image added by this commit:
https://github.com/xoseperez/espurna/pull/1774/commits/2bec5e5b7aac6a777f05b0d894376cc3fff9c3ab

about platformio.ini, I do not use myself, it's hard for me to guess what to write.
it seems that the entry should look similar to itead-sonoff-basic, flash size is the same.

**Comment by mcspr** [comment]
No problem, I'll update the pio files then.
And right,, OTHER section is a better fit (not exactly a switch).

also, for #1458 we should probably in have a general info for tuya upgrade method. Sadly, looking at recent issues at https://github.com/ct-Open-Source/tuya-convert/issues, newest devices do not support it :/

**Comment by reaper7** [comment]
about newest devices, yes, there may be a problem, although tuya has forwarded patch implementation to individual brands. But we know how the eastern producers work (sell and forget) :) Most of the less popular devices, already on sale, will never receive this patch...

**Comment by mcspr** [comment]
I added device page to the wiki and some basic tuya description. Idk if it is worth inserting exact steps from tuya-convert readme though, but I added general description of that patch and how to flash specific .bin

**Pull request merged**
