### PR TITLE
sns: use LastFilter for real time api

### PR DESCRIPTION
**Pull request by drc38**
@mcspr not sure if this is the best way in order to match the description for MQTT when enabling the Real Time Api option  "_Enable this to get unfiltered values in the API (HTTP, MQTT, Prometheus, etc.)_"

### CODE REVIEW

**Comment by drc38** [comment]
Another approach would be to include an if statement to change the reporting to `value.processed` rather than `value.filtered`
`_sensorReport(magnitude, magnitude_index, value.filtered);`

**Comment by mcspr** [comment]
idk. We could call HTTP whenever on our own schedule, so that's the reason we would need to be able to grab read data directly and create our own report / filter / processing with some external program using the data. Also note that there are `{type}MinDelta{number}` and `{type}MaxDelta{number}` magnitude options that may report before normal report count overflow when the value changes happen.

3rd option would be to introduce per-magnitude filter setting?
(something like `{type}Filter{number} => "last"`)

And filter is only created on boot, still, so it should also be able to re-create it when changed?
(with both options targeting filter change)

**Comment by drc38** [comment]
> 3rd option would be to introduce per-magnitude filter setting

Assuming you can set this from web interface that would provide the most flexibility. Ie you could select median, mean, last etc filter per sensor?

**Comment by mcspr** [comment]
> > 3rd option would be to introduce per-magnitude filter setting
> 
> Assuming you can set this from web interface that would provide the most flexibility. Ie you could select median, mean, last etc filter per sensor?

Per 'magnitude' object, something like units.

**Comment by mcspr** [comment]
09c0750c693b5f0546e7fb3ba8329b8c8dfc19f7 allows changing magnitude filter with `${name}Filter${index}`
e.g. `set tmpFilter0 last` and `reset` will create a `LastFilter` object instead of the `MedianFilter`

not in the WebUI, though, idk how frequent that use-case would be. if you still want that, you might want to follow the unit functions with enumerable collections and selects, plus mark it as a 'reboot' action.

**Pull request closed without merging**
