### PR TITLE
Added support for Orvibo B25

### PR DESCRIPTION
**Pull request by plutec**
Orvibo B25 contains an OW8266-02Q that is possible to flash, but I need to create a custom configuration for the device pinout.

### CODE REVIEW

**Comment by plutec** [comment]
It was tested over my device.

**Comment by xoseperez** [comment]
Thank you!

**Comment by nikolas22t** [comment]
How you can put the B25 in flash mode ?

**Comment by plutec** [comment]
Hi Nikolas,
this is the blog post where I wrote all the process. It's in spanish, but
maybe you can translate using google and take a general idea about the
pinout.

https://www.plutec.net/2018/12/cambiando-firmware-orvibo-b25.html

Regards,
--
Antonio Sánchez.

Web: http://www.plutec.net
E-mail: asanchez@plutec.net
Twitter: @plutec_net <http://www.twitter.com/plutec_net>

**Comment by nikolas22t** [comment]
yes but i didn't found how i can put the device in flash mode

**Comment by ColinShorts** [comment]
Ground gpio0

**Comment by plutec** [comment]
Yes, that is!
--
Antonio Sánchez.

Web: http://www.plutec.net
E-mail: asanchez@plutec.net
Twitter: @plutec_net <http://www.twitter.com/plutec_net>

**Comment by richardlimaa** [comment]
What is the password for wifi espurna?

**Pull request merged**
