### PR TITLE
Enable multiple Digital & Events

### PR DESCRIPTION
**Pull request by pilotak**
I know that there is going to be support for specifying all the things dynamically through browser but before that here is enhancement to support it now. This would also help for anyone finding #1815 as there is no code provided, only guidance

### CODE REVIEW

**Comment by pilotak** [comment]
The only thing i don't know is how to set `pwrRatioE` in web-config for each sensor separately

**Comment by mcspr** [comment]
`pwrRatioE<index>`? where index is just a _sensors position
Reset & calibration are a strange ones. Wouldn't it be easier to use direct action calls instead of going through settings and then purging keyvalues?

You might want to also add mapping from the old `..._PIN` to the `...1_PIN`

**Comment by pilotak** [comment]
`pwrRatioE<index>` is not a problem to add but how to hide the unused in browser - there is only section hiding (in html there will be all 8 listed but lets say you have only two setup which would need `display: inherit`).
How do i do "direct action calls"?

**Comment by mcspr** [comment]
Append html settings section programmatically?

By direct actions I meant ws actions:
https://github.com/xoseperez/espurna/blob/fbf2b71749307688f7258ad8235bc0f5d068e926/code/espurna/relay.ino#L698
https://github.com/xoseperez/espurna/blob/fbf2b71749307688f7258ad8235bc0f5d068e926/code/html/custom.js#L430
(thus directly requesting required actions instead of using one-shot settings)

**Comment by pilotak** [comment]
ok, what if i remove pulse-meter from this PR and create a separate once it's done?

**Comment by mcspr** [comment]
sure, that will work

**Comment by mcspr** [comment]
> You might want to also add mapping from the old ..._PIN to the ...1_PIN

Btw, by that I meant to add something here https://github.com/xoseperez/espurna/blob/dev/code/espurna/config/deprecated.h
to remap old defines into the new one + show a warning. Release notice will be there to, but at least VSCode / Atom with PlatformIO will track those messages and show them after build completes if someone uses those in custom header

**Comment by pilotak** [comment]
@mcspr any other request? i think it can be changed otherwise

**Comment by mcspr** [comment]
Don't think so. Any other changes can be made in bulk with other sensors (and maybe even move sensor init to sensor classes themselves)
Sorry for the delay, was I bit busy past 2 weeks.

Also, cc @lbdroid mentioned this https://github.com/xoseperez/espurna/issues/1529#issuecomment-517808484

**Comment by pilotak** [comment]
That's ok, can this be merged?

**Comment by mcspr** [comment]
Done.
I have noticed some pulsemeter changes left over, but they just chain back into themselves and don't change the existing behaviour

**Comment by pilotak** [comment]
I know let's call them preparation for future

**Pull request merged**
