### PR TITLE
Add Magic Home ZJ_LB_RGBWW_L support

### PR DESCRIPTION
**Pull request by wwilsman**
Adds support for [this bulb](https://www.amazon.com/gp/product/B07GGWNQT7/ref=ppx_yo_dt_b_asin_title_o00_s01) sold under the brand "Berennis", but is actually a Magic Home product.

### Photos

IMG_0542
IMG_0543
IMG_0544

### CODE REVIEW

**Comment by mcspr** [comment]
tnx! photos also linked at the https://github.com/xoseperez/espurna/wiki/Hardware-Magic-Home-Light-bulbs
(matching LED controller page. at least for now, maybe in some different format in the future)

**Comment by mwbrown42** [comment]
I've got the same bulb, wired up same as your pictures but I can't make contact to it with the Tasmota tooling.  On Sonoff devices you have to hold down a button on power-up, what did you do for this one?  Thanks!

P.S.  Ooh I now see the blue wire connected to R32.  What pin does that go to on the USB interface board?

**Comment by wwilsman** [comment]
The blue wire is hooked up to GPIO 0 which needs to be grounded. On the USB side it's spliced into the same wire as GND

**Comment by mwbrown42** [comment]
Excellent, thanks for the quick reply!

**Comment by surfarn** [comment]
Hi, how did you manage to remove the led circetboard so you could access the chip? 

I have removed the plastic cover from the bulb and tried to unscrew the bottom, but no sucess, what's the next step? 

Thanks!

**Comment by mwbrown42** [comment]
I couldn't find a way to remove the board from the body of the bulb so I
just soldered the wires onto the pads directly.

You can see the very fine enameled wire I used to make the connections in
my video here:  https://youtu.be/3fpaNGILelw?t=354
--

Mike Brown

"Driving a gasoline sports car is going to feel like a steam engine with a
side of quiche."  Elon Musk

**Comment by surfarn** [comment]
Thank you for the response.

I managed to open up the bulb, just needed to apply a little more force ::)

Den tis 5 maj 2020 kl 14:33 skrev mwbrown42 <notifications@github.com>:

> I couldn't find a way to remove the board from the body of the bulb so I
> just soldered the wires onto the pads directly.
>
> You can see the very fine enameled wire I used to make the connections in
> my video here: https://youtu.be/3fpaNGILelw?t=354
> --
>
> Mike Brown
>
> "Driving a gasoline sports car is going to feel like a steam engine with a
> side of quiche." Elon Musk
>
>

**Comment by superlabguy** [comment]
What config in Tasmota did you use to make it work?

**Comment by wwilsman** [comment]
@superlabguy if you're referring to the configuration template, here is mine:

```
{"NAME":"RGBCW Light","GPIO":[0,0,0,0,38,37,0,0,40,41,39,0,0],"FLAG":0,"BASE":18}
```

**Comment by superlabguy** [comment]
thanks.  Exactly what i was looking for.

**Pull request merged**
