### PR TITLE
Fix WS memory leak when disconnected

### PR DESCRIPTION
**Pull request by mcspr**
Fix #1843 & #1851 queues not clearing when disconnected
Fix continuously filling ws message queue when disconnected

### CODE REVIEW

**Comment by davebuk** [comment]
Hi Max

I am getting some errors when trying to build using the latest dev branch. Could changes made to ws.ino be the reason?  See below:

```
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:643:18: error: '_ws_client_data' was not declared in this scope
     auto& data = _ws_client_data.front();
                  ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPost(const ws_on_send_callback_f&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:749:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(cb);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostAll(uint32_t, const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:753:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(client_id, cbs, ws_data_t::ALL);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostAll(const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:757:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(0, cbs, ws_data_t::ALL);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostSequence(uint32_t, const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:761:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(client_id, cbs, ws_data_t::SEQUENCE);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostSequence(const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:765:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(0, cbs, ws_data_t::SEQUENCE);
     ^
*** [.pio\build\wemos-d1mini-relayshield\src\espurna.ino.cpp.o] Error 1
```

**Comment by davebuk** [comment]
Hi Max

I am having issues building with the latest dev branch and get the following errors:

```
Compiling .pio\build\wemos-d1mini-relayshield\liba5b\ESP8266WiFi\ESP8266WiFiScan.cpp.o
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:132:1: error: 'queue' in namespace 'std' does not name a type
 std::queue<ws_data_t> _ws_client_data;
 ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void _wsHandleClientData(bool)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:637:24: error: '_ws_client_data' was not declared in this scope
C ompiling .pio\build\wemos-d1mini-relayshield\liba5b\ESP8266WiFi\WiFiClient.cpp.o
    if (!connected && !_ws_client_data.empty()) {
                        ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:642:9: error: '_ws_client_data' was not declared in this scope
     if (_ws_client_data.empty()) return;
C ompiling .pio\build\wemos-d1mini-relayshield\liba5b\ESP8266WiFi\WiFiClientSecure.cpp.o
        ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:643:18: error: '_ws_client_data' was not declared in this scope
     auto& data = _ws_client_data.front();
                  ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPost(const ws_on_send_callback_f&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:749:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(cb);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostAll(uint32_t, const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:753:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(client_id, cbs, ws_data_t::ALL);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostAll(const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:757:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(0, cbs, ws_data_t::ALL);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostSequence(uint32_t, const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:761:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(client_id, cbs, ws_data_t::SEQUENCE);
     ^
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino: In function 'void wsPostSequence(const ws_on_send_callback_list_t&)':
C:/Users/Samsung Laptop/Documents/PlatformIO/ESPurna dev/espurna/code/espurna/ws.ino:765:5: error: '_ws_client_data' was not declared in this scope
     _ws_client_data.emplace(0, cbs, ws_data_t::SEQUENCE);
     ^
*** [.pio\build\wemos-d1mini-relayshield\src\espurna.ino.cpp.o] Error 1
```

**Comment by mcspr** [comment]
Adding `#include <queue>` somewhere in the prototypes.h will fix this, I missed that homeassistant & alexa include those locally

**Comment by davebuk** [comment]
I had homeassistant and alexa not defined to keep the size down. I defined alexa support and it builds fine now.

**Comment by mcspr** [comment]
Right. https://github.com/xoseperez/espurna/pull/1860/commits/b652ee6e3439f0fd5c1a7a05f8d4658012689408 is what I meant though, merged as part of #1860

**Comment by davebuk** [comment]
It was easier for me to test by enabling alexa rather than modifying core files. :-)

**Pull request merged**
