### PR TITLE
Tuya support

### LINKED ISSUE #1729: Firmware for Tuya dimmer
Hi all. How can I look to build a firmware for the following device:
https://www.amazon.co.uk/OurLeeme-Dimmer-Control-Function-Compatible/dp/B07RHCFKQ2

I have got one coming this week so I won't know what chip setup is inside but will post when I do. I wonder if the Sonoff wall dimmer will work as base code?

### PR DESCRIPTION
**Pull request by mcspr**
Test build to resolve #1729 

Need to:
- <s>fix broker interface</s><br>see broker.h, simplify brokerPublish signature. this breaks backwards compatibility, but I guess I could restore it with old "type(int)" dispatching to a proper TBroker
- <s>take a look again if this is really relay / light provider</s><br>(note: this could work outside of relay module completely, but wait until other providers are configured as such)
- <s>clean-up tuya classes</s>
- <s>avoid breaking existing modules</s>

### CODE REVIEW

**Comment by mcspr** [comment]
@tonilopezmr Small example of how `pio test` works https://github.com/xoseperez/espurna/pull/1997/commits/b6680304efef5c91cf9db9f720489ed2bcc65a06. This probably needs some proper Arduino framework layer, perhaps it could even be reused from the current [esp8266/Arduino testing framework](https://github.com/esp8266/Arduino/tree/master/tests/host) (...but the last time I got lost in mocks dependencies implemented there...)

I also wonder why tf I needed view objects instead of copying the data, restricting copy constructors.

**Comment by mcspr** [comment]
@davebuk btw I will merge this tomorrow.
Some changes to the logic are seemingly harmless, but I need to dig up the emulator program again just to be sure.

**Comment by davebuk** [comment]
Great. I'll build a 1.14.0dev version once merged and then test.

**Comment by mcspr** [comment]
Note that unlike previous version, I tried to rework boot sequence to actually try to make use of `relayBootN` setting / "Relay Boot mode".

**Comment by davebuk** [comment]
I have made a 1.14.0dev 2.5.2 core build and the dimmer is working fine. Really great work. I'm away for a few days but if you want any further tests running on this build, I'll see what I can do.

Thanks again.

**Comment by mattster98** [comment]
I got some plug-in relay modules that happily came over to Espurna with the tuya-convert process.  Can anyone point me toward how to build for a relay module?  Generic relay firmware doesn't work.

**Pull request merged**
