### PR TITLE
Handle all time zone/dst from posix database

### PR DESCRIPTION
**Pull request by Diramu**
I've just created a pull request to NtpClient with take all necessary parameters to fully describe timezones extracted from https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv

A script html/TZupdate.pl reads this file creating TZ.js for index.html to select a time zone entry.
Also  creates TZ.h included by ntp.ino to pass the select timezone parameters to NtpCleint.

TZupdate.pl can create  a table will all time zones, or just a single time zone to reduce the size.

### CODE REVIEW

**Comment by Valcob** [comment]
@Diramu, 53 files changed for a simple NTP -TZ update? Please change only the required files :)
Also do a git pull from dev and merge into your branch before creating a PR just to ensure that your code is not too far behind the current dev branch. Thanks in advance for your work!

**Comment by Diramu** [comment]
> @Diramu, 53 files changed for a simple NTP -TZ update? Please change only the required files :)
Agree, only index.html and ntp.ino really changed, plus a couple new files.
> Also do a git pull from dev and merge into your branch before creating a PR just to ensure that your code is not too far behind the current dev branch. Thanks in advance for your work!

I need a little help understanding git. 
> git branch
  dev
  master
* origin
> git pull
Already up to date.
Heres my .git/config:
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "upstream"]
	url = https://github.com/xoseperez/espurna.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "dev"]
	remote = upstream
	merge = refs/heads/dev
[remote "origin"]
	url = https://github.com/Diramu/espurna.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "origin"]
	remote = origin
	merge = refs/heads/origin

How do I pull from dev?

**Comment by Diramu** [comment]
I was going to close this PR, and recreated it from a fresh clone of dev. But it appears to be conflict free.  I don't understand the failed Travis-ci build failed.  I expect the problem , this code does require my changes to NtpClient (https://github.com/gmag11/NtpClient/pull/76)

**Comment by mcspr** [comment]
@Diramu You could've referenced your NtpClient repo inside platformio.ini to check that (`<url>#commit`)

btw you still have inconsistent files. See (it is git ... -- PATH)
`git diff upstream/dev -- code/html`
`git diff upstream/dev -- code/espurna/config`
`git diff upstream/dev -- code/espurna/*.ino`
That would've been better handled manually, checking out `dev` and using some visual diff/merge tool to apply your changes piece by piece (see `git-add` man and `-p` option, for starters), comparing final files with `upstream/dev` versions

**Comment by Diramu** [comment]
I'm going to closes this, and recreate it with a fresh clone of dev.  Thanks for the pointers.

**Pull request closed without merging**
