### PR TITLE
Add support for the LSC LED LIGHT STRIP

### PR DESCRIPTION
**Pull request by sehraf**
This LED strip is sold by ACTION in Germany and comes with a Tuya (TYWE3L) chip. It can be "freed" by using tuya-convert. It has (yet another) IR remote control that uses another set of codes. Which is added, too. The color codes are copies from SET 1 and 2. 
I kind of think that they don't match my remote control but since i'm using my smart home system for controlling, i don't care enough to figure out the correct color codes.

The circuit board supports also a CW channel on PIN 5 (which is not used on by version), nevertheless I've added a comment in case anybody has a similar device with CW.

cpu-pinout

### CODE REVIEW

**Comment by mcspr** [comment]
Thanks!

**Comment by sehraf** [comment]
Tanks for merging this. Sadly you cut off the ota lines from platformio.ini https://github.com/xoseperez/espurna/pull/2065/commits/a8253ae06fdc88452cf4e1335231de289dce60f6#diff-25ef070b6156fdfa35dd363916f0f98aR1713

**Comment by mcspr** [comment]
Yep, git merge is a weird at the end of file for some reason.
Will fix while merging the last device in the queue - #2063

**Comment by alexsahka** [comment]
Any build 1M firmware for this module? Thanks!

**Pull request merged**
