### PR TITLE
Added BESTEK_MRJ1011

### PR DESCRIPTION
**Pull request by InduPrakash**

### CODE REVIEW

**Comment by InduPrakash** [comment]
Created a wiki page https://github.com/InduPrakash/espurna/wiki/Hardware-Bestek-MRJ1011 .. not sure how to pass the images.

**Comment by xoseperez** [comment]
Merged. Thank you!

**Comment by mcspr** [comment]
drag-n-drop works in prs and issues and create githubusercontent urls
what I was mentioning earlier in gitter is to use this feature and paste urls in the wiki

```
![octocat-spinner-128](https://user-images.githubusercontent.com/132763/46041410-63f3cd00-c11b-11e8-9a6b-f465057499be.gif)
```
octocat-spinner-128

**Comment by InduPrakash** [comment]
bestek-mrj1011-cover
bestek-mrj1011-inside
bestek-mrj1011-tywe2s
bestek-mrj1011-tywe2s-back
bestek-mrj1011

**Comment by InduPrakash** [comment]
I updated the main wiki and created a sub page. I guess I could have added the pics to images/devices folder but I did not because existing tear down pictures were coming from somewhere else.

**Pull request merged**
