### PR TITLE
Add new device - iWoole Smart LED Table Lamp

### PR DESCRIPTION
**Pull request by ColinShorts**
This is for the small round lamp, there is a taller version that may/may not use the same config.

Flashing the device is reasonably simple, you just need to open it and dismantle everything to solder wires onto the ESP-M2 module as normal.

### CODE REVIEW

**Comment by ColinShorts** [comment]
Sorry about the noise, the standard 4 files are in commit a4afefa, I had symlinked pre-commit into the hooks, so it looks to have touched README.md too.

**Comment by mcspr** [comment]
FIY PR history can be discarded via "Squash and merge" so that does not matter much

**Comment by ColinShorts** [comment]
Thanks @mcspr I'll try cleaning it up for next time 😁

**Comment by xoseperez** [comment]
Great! Merged!

**Comment by mcspr** [comment]
@ColinShorts no worries :)
@xoseperez as an example, homeassistant and nodemcu do this to not burden pr creator with 'git merge --squash' ing: 
https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github

it is 50/50 cosmetic and useful and mostly done to avoid strange history https://github.com/xoseperez/espurna/compare/2e4f1c319454...e7845ac83dfa86164116e5fa8d67f2c82914d312
or using git log without --no-merges will be confusing

**Comment by ColinShorts** [comment]
@xoseperez The README.md change was pulled through, so the branch and build links are now pointing to my fork. This was caused by me using the pre-commit hook - sorry for the trouble.

**Pull request merged**
