### PR TITLE
Sonoff 4CH Pro - Add more telecomand 433Mhz

### PR DESCRIPTION
**Pull request by Thecyp31**
Hi all,

I very like the espurna firmware, but i have one question.

I have some Sonoff 4CH Pro, and i want manage the 4 channel by rf 433 telecomand.

But i can only add 1 telecomand to 1 channel, i want add X ( 2 , 3 or more ) telecomand to 1 channel.

It's possible to upgrade this support with this firmware ?

Thanks a lot

### CODE REVIEW

**Comment by mcspr** [comment]
@Thecyp31 Did you mean to create issue instead? I am not seeing any changes. This is just difference between `master` and `dev`.

As for more that 1 rf code per channel - thats on Itead, they only remember last one learned.

**Comment by Thecyp31** [comment]
@mcspr
Sorry i am a new member of github. I have think  "the pull request" are like demand.
For my demand it is not possible to store more code on the firmware, not just the last ?

**Comment by mcspr** [comment]
RF codes are not controlled by espurna. When RF signal is received all that it sees is a button press.

No worries. [Pull requests](https://help.github.com/articles/about-pull-requests/) are about changes you made and want to share.

**Comment by Thecyp31** [comment]
Ok thanks for the explanation :) so i delete this pull request :)

**Pull request closed without merging**
