### PR TITLE
add support for shelly1 relay

### PR DESCRIPTION
**Pull request by abmantis**
Support for the new Shelly1 relay.

Official page: https://shelly.cloud/product/shelly-1-open-source/
Docs: http://shelly-api-docs.shelly.cloud/#shelly1-relay-index

### CODE REVIEW

**Comment by salopette** [comment]
Work shelly 1 with espurna?
Or tasmota Firmware?

**Comment by abmantis** [comment]
By the way, I used IwIP v2 and a flash size of 2M (1M SPIFFS). Could that (specially IwIP) be the cause for the device reseting itself?

**Comment by xoseperez** [comment]
You don't need SPIFFS for ESPurna. Simply use the 1M layout size. Current stable version still uses SDK 2.3.0, not 2.4.X, you might want to test with that.

**Comment by abmantis** [comment]
But there should be no issue in using a 2M layout with 1M SPIFFS, right? 
I'll try 2.3.0 then. What is the best way to debug this kind of behaviour?

**Comment by xoseperez** [comment]
The best way when there is a reset is to debug it wired. I would use the 12V input and connect RX, TX and GND from the debug port to your computer, open a serial monitor and play with it.

**Comment by salopette** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/2789#issuecomment-415027795

**Comment by ascillato** [comment]
Let's centralize all shelly requests in one issue #3559

**Comment by salopette** [comment]
how is it going to work with Shelly2?

**Comment by xoseperez** [comment]
I have just pushed support for the Shelly2 in the `dev` branch.

**Comment by jsponz** [comment]
@xoseperez Good news! What about the power meter? It has a power monitoring IC MCP39F501 (https://www.microchip.com/wwwproducts/en/MCP39F501)

**Comment by xoseperez** [comment]
The schematic for the Shelly2 is not available, is it?

**Comment by fab33** [comment]
@xoseperez the power meter is working with Tasmota : https://github.com/arendst/Sonoff-Tasmota/wiki/Shelly-1-and-2

**Pull request merged**
