### PR TITLE
Build with platformio 4

### PR DESCRIPTION
**Pull request by mcspr**
cc @Niek , can you please try the ESPURNA_PIO_SHARED_LIBRARIES=1 stuff?

- use generic env section
- all envs are streamlined to just board=... and build_flags=...
- travis does not use py3 (yet, but i wonder if we can just use py3 syntax straight away)
and references current rc1 commit https://github.com/platformio/platformio-core/commit/8d459d86d33992129726ef177ed24fe8a00e9b75, since there is no pre-release on pypi

nightly builder can then verify that every env builder works, at least dumb mistakes like flash size would be caught

### CODE REVIEW

**Comment by Niek** [comment]
I like the massive platformio.ini cleanup :) Building with ``ESPURNA_PIO_SHARED_LIBRARIES=1`` works fine, but the ``shared_libdeps_dir`` (code/libraries) is not in the .gitignore - you might want to add that.

**Comment by mcspr** [comment]
PR & documentation:
https://github.com/platformio/platformio-core/issues/1643
http://docs.platformio.org/en/latest/projectconf/section_env.html#global-scope-env

Will update .gitignore

Previous .piolibdeps catching looks iffy too, probably it should use global storage based on travis env (~/.platformio/lib)
I also wonder if there's any problem always having shared libraries/ dir enabled

**Comment by Niek** [comment]
I'm not sure if it's a bug in PIO (4.0-rc4) or related to this PR, but I noticed building with a core different than 2.4.x I get this error:
```python
TypeError: expected string or buffer:
  File "~/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 126:
    env.SConscript("$BUILD_SCRIPT")
  File "~/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/~/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
    exec _file_ in call_stack[-1].globals
  File "~/.platformio/platforms/espressif8266/builder/main.py", line 255:
    env.get("UPLOAD_PORT", ""))):
  File "~/.platformio/penv/lib/python2.7/re.py", line 141:
    return _compile(pattern, flags).match(string)
```

**Comment by mcspr** [comment]
Is this using -ota env and platform = espressif8266@2.2.2, with defined ESPURNA_IP & ESPURNA_AUTH (if yes, what is ESPURNA_IP value)?
What is env.get("UPLOAD_PORT") value? You can use print(), somewhere before that failing re.match call.

**Comment by Niek** [comment]
Yes, @2.2.2 and -ota - but I just noticed I forgot to update my env from ``common.upload_port`` to ``common.ota_upload_port``, my bad. However, after changing this the error becomes (same error with non-ota envs):
```python
KeyError: 'FRAMEWORK_ARDUINOESP8266_DIR':
  File "~/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 134:
    env.SConscript(item, exports="env")
  File "~/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
    return _SConscript(self.fs, *files, **subst_kw)
  File "~/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
    exec _file_ in call_stack[-1].globals
  File "~/Documents/Code/twine-firmware/code/extra_scripts.py", line 145:
    patch_lwip()
  File "~/Documents/Code/twine-firmware/code/extra_scripts.py", line 100:
    framework_dir = env["FRAMEWORK_ARDUINOESP8266_DIR"]
  File "~/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 410:
    return self._dict[key]
```
Maybe this env var is no longer set in 2.2.2?

**Comment by Niek** [comment]
This fixed it for me (in extra_scripts.py):
```python
framework_dir = platform.get_package_dir("framework-arduinoespressif8266")
```

**Pull request merged**
