### PR TITLE
Add support for Lohas 9W bulbs

### PR DESCRIPTION
**Pull request by steveway**
It seems to be very similar to the ITead Sonoff B1, so it's based on that.
This should be the official product page if I'm not mistaken:
http://www.lohasled.com/9w-a19-p00064p1.html

### CODE REVIEW

**Comment by Wikibear** [comment]
Tried out today... Found ITead is similar but not same.

`#elif defined(ITEAD_SONOFF_B1)

    // Info
    #define MANUFACTURER        "LOHAS"
    #define DEVICE              "RGBW 9W"
    #define RELAY_PROVIDER      RELAY_PROVIDER_LIGHT
    #define LIGHT_PROVIDER      LIGHT_PROVIDER_MY92XX
    #define DUMMY_RELAY_COUNT   1

    // Light
    #define LIGHT_CHANNELS      5
    #define MY92XX_MODEL        MY92XX_MODEL_MY9231
    #define MY92XX_CHIPS        2
    #define MY92XX_DI_PIN       13
    #define MY92XX_DCKI_PIN     15
    #define MY92XX_COMMAND      MY92XX_COMMAND_DEFAULT
    #define MY92XX_MAPPING      0, 1, 2, 3, 4
    #define LIGHT_WHITE_FACTOR  (0.1)             `

You have then 5 Channels: R,G,B and 2 White LED's and at this Point i don't understand if that is well or not.

**Comment by solbergw** [comment]
I tried this out on E26 9W, RGB Works, White temperature does not change.  Are there further possible outputs that can be mapped beyond 0-4.

**Comment by steveway** [comment]
Mhh, I moved recently and can't test my light at the moment.
I need to reflash it for that, currently I don't have the ability because I'm missing a place to solder here.
I think if I remember correctly the temperature is controlled by two different sets of white LEDs, I'm not sure if Espurna does support controlling that this way yet.

**Comment by Wikibear** [comment]
Are you sure that there is a real white channel??? This Lamp ist RGB only...

**Comment by solbergw** [comment]
I cracked open the bulb to find out what was really happening.  Channels 0-2 control the RGB LEDs, channel 3 controls (4 white LEDs) and channel 4 controls (4 white LEDs).  All 8 of the white LEDs are the same temperature.   With the factory installed firmware, I set the bulb to a warm temperature and it uses the white LEDs + the red LEDs.  When I set the bulb to a cool temperature it only uses the white LEDs.

**Pull request merged**
