### PR TITLE
webui: Improve Scheduler type interface

### PR DESCRIPTION
**Pull request by opticron**
The scheduler type selection is not intuitive as there is no prompt to change the empty drop-down box to another value. This makes it obvious that something needs to be selected.

### CODE REVIEW

**Comment by mcspr** [comment]
What about reportValidity() instead?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/reportValidity

Non-interactive part
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/checkValidity

having more text in an already pretty narrow input might be too much?
ed26dbd attempts to force everything through validity checks before being allowed to apply any settings, I'd expect this would be much more apparent than select label. for schedule inputs, this generates a warning immediately after template is injected. plus, there is also an annoying warning after editing the field for basic text inputs

**Comment by opticron** [comment]
Thanks for adding that. Does that commit obsolete this change, then?

**Comment by mcspr** [comment]
"makes it obvious" that elem is required when editing should be solved, yes

**Comment by opticron** [comment]
Ack

**Pull request closed without merging**
