### PR TITLE
Streamline correction settings

### PR DESCRIPTION
**Pull request by mcspr**
fix? #2231 

- group correction settings for known types, add webui detection, relax constraints for values
- de-hardcode webui magnitude and error types

### CODE REVIEW

**Comment by davebuk** [comment]
Did you want me to try your code and build over the weekend or shall I wait until you have merged into the main xoseperez dev code?

**Comment by mcspr** [comment]
If you can try it out like this, please do. It would be good to verify nothing else in the sensors breaks because of this change.

**Comment by davebuk** [comment]
Looking good!
These are from a BME280.
**BEFORE**
bmx01
**AFTER**
bmx02

The order is which Pressure and Humidity are shown between the status page and sensor page are different but you wouldn't normally be looking at both pages at the same time.

MQTT values are correct and seen by openHAB.

I can try a Lux later today if you like?

**Comment by davebuk** [comment]
Second device with BH1750 sensor.
**BEORE**
lux01
**AFTER POSITIVE CORRECTION**
lux02
**AFTER NEGATIVE CORRECTION**
lux03

**Comment by mcspr** [comment]
Thanks!

I did not notice the order. Corrections page is generated outside of sensor class, so numerical sorting comes into play (Temperature, Humidity, Pressure). Sensor though uses a special logic to exclude humidity when sensor happens to be BM**P**280, so naturally it is the last one.

**Pull request merged**
