### PR TITLE
RF/RFBRIDGE Update

### LINKED ISSUE #1586: Ticker.h error for  "rfb_ticker.attach_ms" - ITEAD_SONOFF_RFBRIDGE
Espurna Version [1.13.4] 2019-02-23
rc2.5.0

ITEAD_SONOFF_RFBRIDGE

**rfbridge.ino line 264**
        _rfb_ticker.attach_ms(RF_SEND_DELAY, _rfbSend);
to
        _rfb_ticker.attach_ms(RF_SEND_DELAY, **_rfbSendMe**);

**rfbridge.ino line 221**
void _rfbSend() {
to
void **_rfbSendMe**() {

### LINKED ISSUE #1590: Compile error with SonOff rf bridge 433 RF_RAW_SUPPORT
This is the Visual Studio compilation output with de errors with RF_RAW_SUPPORT = 1. How Can I solve the errors? Or is the latest source faulty?

```
Compiling .pioenvs\itead-sonoff-rfbridge\src\espurna.ino.cpp.o
C:/Users/Frans/Documents/espurna-dev/code/espurna/rfbridge.ino: In function 'void _rfbParseCode(char*)':
C:/Users/Frans/Documents/espurna-dev/code/espurna/rfbridge.ino:493:27: error: 'isRFRaw' was not declared in this scope
if ((len > 0) && (isRFRaw || len != RF_MESSAGE_SIZE)) {
^
C:/Users/Frans/Documents/espurna-dev/code/espurna/rfbridge.ino: In lambda function:
C:/Users/Frans/Documents/espurna-dev/code/espurna/rfbridge.ino:612:38: error: invalid conversion from 'const char*' to 'char*'
[-fpermissive]
_rfbParseCode(payload);
^
C:/Users/Frans/Documents/espurna-dev/code/espurna/rfbridge.ino:471:6: error:   initializing argument 1 of 'void _rfbParseCode(char*)' [-fpermissive]
void _rfbParseCode(char * code) {
^
*** [.pioenvs\itead-sonoff-rfbridge\src\espurna.ino.cpp.o] Error 1
================================================= [ERROR] Took 7.65 seconds 
```

### PR DESCRIPTION
**Pull request by mcspr**
fixes #1590 
fixes #1586 
maybe #1014 

- redefine RF_SUPPORT to be generic RF support. Use RFB_DIRECT=1 for RCSwitch implementation, RFB_DIRECT=0 for EFM8 controller.
- remove optional RF RAW support.
- rename RF_PIN -> RFB_RX_PIN, fix hardware and general headers
- aand small fix for Core 2.5.0 compilation.

I have only tried building itead-sonoff-rfbridge bin with RFB_DIRECT=0/1, to see if everything is in place. No live testing done yet.

cc @InduPrakash (https://github.com/xoseperez/espurna/issues/1014#issuecomment-482077321)

### CODE REVIEW

**Comment by InduPrakash** [comment]
In relay.ino, can "#if RELAY_PROVIDER == RELAY_PROVIDER_RFBRIDGE" around rfbStatus() calls be replaced with check for RF_SUPPORT?

**Comment by InduPrakash** [comment]
The RF section is missing in web image due to this check:
```
#if defined(ITEAD_SONOFF_RFBRIDGE)
    #ifndef WEBUI_IMAGE
        #define WEBUI_IMAGE    WEBUI_IMAGE_RFBRIDGE
    #else
        #undef WEBUI_IMAGE
        #define WEBUI_IMAGE    WEBUI_IMAGE_FULL
    #endif
#endif

```

**Comment by InduPrakash** [comment]
MQTT messages is working for my nodemcu device as before.

I saw this explicit check for ITEAD_SONOFF_RFBRIDGE (in migrate.ino), does it need to be adjusted?
`#elif defined(ITEAD_SONOFF_RFBRIDGE)`

**Comment by mcspr** [comment]
> RELAY_PROVIDER == RELAY_PROVIDER_RFBRIDGE" around rfbStatus() calls be replaced with check for RF_SUPPORT?

IDK about that. The way providers work now, it will force you to use RELAY_PROVIDER_RELAY with real pins. Maybe for some other PR.

Some fixes. *(kinda delayed, because I could not find rf receiver / transmitter yesterday)*
- fixed `defined(ITEAD_SONOFF_RFBRIDGE)` checks
- runtime configurable RX & TX pins, WebUI section to configure them
- configurable repeat value
- moved sending to loop instead of ticker (allow more repeats, yield())

I was having trouble receiving anything with rc-switch. It worked for some time, but then suddenly stopped and I could no longer see data. Even with rc-switch ReceiveDemo example :/
One last thing is to test with Sonoff...

**Comment by InduPrakash** [comment]
The new changes work as intended.

Is configuring the Rx/Tx pins from WebUI really useful? I mean it can be useful when prototyping but pin configuration would probably need a new image.

"Repeats" value is only relevant for RFBridge, right? It is always 1 for RFB_DIRECT.

**Comment by mcspr** [comment]
Is configuring the Rx/Tx pins from WebUI really useful? I mean it can be useful when prototyping but pin configuration would probably need a new image.

True, but it can always be moved. At least it is a place outside terminal (or config backup) to disable / enable them. Although, seeing it again, i did mess up the placement and should've added a hint text.

"Repeats" value is only relevant for RFBridge, right? It is always 1 for RFB_DIRECT.


"Repeat" means different thing depending on context. For sonoff, it will send serial command N times, because EFM8 does repeats on it's own (~4 times, i think). RCSwitch has a setting for repeats though:
https://github.com/xoseperez/espurna/blob/056f7ebf079bad9cde4bd3f529b04a5a83695fdd/code/espurna/rfbridge.ino#L800
(which was previously hard coded as 6)

Tested with Sonoff, everything works too.

**Comment by InduPrakash** [comment]
I see what you were referring to; I was referring to the _times_ setting on message which put it back on the queue > 1. I am using an 315Mhz external tx/rx and it works fine. My switch is a bit weird though and based on some suggestions ended up using a special version of RCSwitch (https://github.com/Martin-Laclaustra/rc-switch.git#protocollessreceiver).

**Comment by mcspr** [comment]
Right. This was added here:
https://github.com/xoseperez/espurna/commit/ab175de48a0fa5b1788bf3e82823d804ba233242#diff-33b53c8048ea432beaa4729de07e48b8R212
I assume a bunch of delayMicroseconds calls to switch GPIO on and off will trigger software watchdog if timings are large enough:
https://github.com/sui77/rc-switch/blob/a9da9c36820b02fc5613dfe2437e1187bcf5b402/RCSwitch.cpp#L523-L533

Unspecified, it defaults to 10:
https://github.com/sui77/rc-switch/blob/a9da9c36820b02fc5613dfe2437e1187bcf5b402/RCSwitch.cpp#L104

Or it can be a separate option altogether.

**Pull request merged**
