### PR TITLE
Making Emon Sensor params overrideable

### PR DESCRIPTION
**Pull request by djwmarcx**
Making Emon Sensor params overrideable.
Also fixing wrong comment reported at #1277

### CODE REVIEW

**Comment by djwmarcx** [comment]
Also, I added two commits to prevent the adminPass to be leaked through the terminal

**Comment by xoseperez** [comment]
The params part is OK. I would not commit the adminPass check you are doing. There are a number of ways to "leak" that password anyway.

**Comment by djwmarcx** [comment]
Is there a plan to review all those adminPass leak points and fix them together or is just out of scope?

I agree that with this type of devices EEPROM will be always readable using "hard way" methods, but I personally think that every security level it's valuable.

**Comment by mcspr** [comment]
@djwmarcx IMO `get` is not the problem here and it only needlessly complicates things. You can just as easy run `eeprom.dump` / `flash.dump` / `keys` / `config` from terminal or just download config json via /config endpoint.
And given that you are changing EMON comments, it is out of scope for sure.

**Comment by djwmarcx** [comment]
Thanks for your clarification @mcspr

How we can proceed to apply just EMON changes? I need to revert my changes on admin pass and push?

**Comment by mcspr** [comment]
Yep. For example, this will reset changes to settings.ino and restore it to the way it was in your initial commit on this branch:
```console
$ git checkout ff14e96 -- code/espurna/settings.ino
$ git commit -m 'revert adminPass changes'
```
Another option is to run `git revert <sha>` on each individual commit

**Pull request merged**
