### PR TITLE
Make switch schedules work again

### PR DESCRIPTION
**Pull request by wysiwyng**
Apparently JS makes a difference between 1 and "1"

### CODE REVIEW

**Comment by xoseperez** [comment]
Mmmm... didn't notice that problem when testing. What about doing a parseInt to be sure about the output type?

**Comment by wysiwyng** [comment]
That could work too I think. When I was testing, regardless of the button I clicked in the schedule tab, a light schedule was always added. This change fixed it for me, though I must say I am not the greatest JS artificionado...

**Comment by mcspr** [comment]
Maybe this is happening because of this? It is actually a string when sent to the client.
https://github.com/xoseperez/espurna/blob/8777d29f7c780bc14396a795c947d777b6d97262/code/espurna/scheduler.ino#L29
Like here, that probably missing `toInt`
https://github.com/xoseperez/espurna/blob/8777d29f7c780bc14396a795c947d777b6d97262/code/espurna/scheduler.ino#L128

**Comment by wysiwyng** [comment]
@mcspr, yes that is also part of the problem, it is however nested in somewhere else also. 1bab8e0 should fix this properly, I changed all occurrences of the variable schType to an integer.

**Comment by zafrirron** [comment]
Thanks @wysiwyng & @xoseperez 

this fix Works like a charm...

**Pull request merged**
