### PR TITLE
Travis parallel builds

### PR DESCRIPTION
**Pull request by lobradov**
Make travis run in parallel. 
Minor improvement for dev branch, but major for full releases. 
Based on months-old work by @mcspr and myself.

### CODE REVIEW

**Comment by mcspr** [comment]
🎊 Hello.

What about explicit names for matrix?
When script is `./build.sh $BUILD_ME`, env BUILD_ME=travis01, BUILD_ME=travis02 ... will buil explicit test binaries by name. That way you can just use BUILD_ME=itead-sonoff-basic for release (plus branch condition ofc)

Also see #950 (where ./build.sh is wrapped, but doing that explicit env call) for working parallel release test. I wonder if there is a way bundle hardware config instead of building arduino core 90 times for each binary :/

**Comment by lobradov** [comment]
You can still use name of the build as parameter, but in case you omit it AND you add `-p`, builds will go parallel. I personally am against manual parallelization (manually splitting target builds into groups), but than again, it's just me.

The only change compared to old build script is the `-l` instead of `list`, for the sake of consistency.

**Comment by mcspr** [comment]
It does show OK but awk actually broke

Well, awk does splits jobs by number already. Consider if ini is parsed and pre push commit does awk job listing all the jobs into the travis yml. Why stop at 4 jobs :) *...limit is 200...*

**Comment by lobradov** [comment]
> It does show OK but awk actually broke

I must have missed something... what do you mean?

**Comment by lobradov** [comment]
pfft, have no clue where that backslash came from. anyway, it's fixed now, but I see Travis randomly failing, which I think was the original issue.

**Comment by lobradov** [comment]
It would be super-good if we had a bucket with S3 storage somewhere, so that we can create build environment in one task, store pio + pio libs + npm + web UI, and then use that in parallel tasks that depend on the first one.
 
I guess, without it, this is the best/fastest we can get with this logic of building. We're still left with alternatives: 
- Your wrapped build.sh, potentially massively parallelized (which I'm sure Travis folks would love ;)
- Docker builder 
- Circle-ci or some other CI service.

**Comment by mcspr** [comment]
https://github.com/esp8266/Arduino/commit/a1a9b99af664b0ab084c7a1ffddecd53888e2e41 arduino/esp8266 does it this way too, using bash math instead of awk.

Because there are 3 travis firmwares one job does nothing but build webui. job count can still be fixed for test, just use this split for releases until there are less of them to build. Other ci (i mean, all of them) do have saner options for doing this chain, but still require building N images.

**Comment by mcspr** [comment]
@lobradov What I meant by splitting tests from release:
https://github.com/lobradov/espurna/compare/parallel-travis...mcspr:checkme

https://travis-ci.org/mcspr/espurna/builds/397608343 - untagged commit (push, pr)
https://travis-ci.org/mcspr/espurna/builds/397609136 - tagged commit adds 4 builder jobs, does the matrix thing

**Comment by xoseperez** [comment]
This is a massive improvement when releasing! 
How would it work for pre-release versions or something like nightly versions?

**Comment by lobradov** [comment]
Nightly builds are a matter of Travis settings (trigger nightlies) and publishing.

I'm out on a vacation with only but a phone access to emails, but I'm sure Max can help if you merge this PR and let him work on it.

//_ on phone

**Comment by mcspr** [comment]
True. For nightlies deploy provider can put releases somewhere else, despite what docs / issues say (jeez, I hope that will not be changed) - $TRAVIS_REPO_SLUG controls where to put releases. `export ...` before_deploy can change that because environment is not reset.

So I'll put that branch as PR. *I did open pr against this pr, but I figure that is not going to be merged soon :)*

**Pull request merged**
