### PR TITLE
Fixed size json payload & other WS bugfixes

### LINKED ISSUE #1731: Multiple web clients cause crash
I´ve tried 1.13.5 with a Son Off pow r2. It was working for more than a day, and I made log in from another browser (I had a browser in one computer opened and monitoring it every few hours) and then I opened the second one in another computer and made login again, the Sonoff was rebooted.

I paste the information from the crash command.

[038911] [DEBUG] Latest crash was at 179498184 ms after boot
[038915] [DEBUG] Reason of restart: 2
[038918] [DEBUG] Exception cause: 29
[038921] [DEBUG] epc1=0x4020e0de epc2=0x00000000 epc3=0x00000000
[038925] [DEBUG] excvaddr=0x00000000 depc=0x00000000
[038928] [DEBUG] sp=0x3ffffd20 end=0x3fffffb0
[038931] [DEBUG] >>>stack>>>
[DEBUG] 3ffffd20: 3fff872c 3fffa808 3fff07b4 4020ccd9 
[DEBUG] 3ffffd30: 00000aac 00000aac 00000aac 00000000 
[DEBUG] 3ffffd40: 00000014 3fff710c 3fff07b4 40215d8d 
[DEBUG] 3ffffd50: 00000000 00000000 00000000 3fff624c 
[DEBUG] 3ffffd60: 00000014 3fff624c 3fff6f98 40215e1b 
[DEBUG] 3ffffd70: 3ffe9468 00000000 3fffaa34 00002000 
[DEBUG] 3ffffd80: 3fff7146 00000014 0000000a 0000000f 
[DEBUG] 3ffffd90: 00000059 00000050 3ffffdd0 00000000 
[DEBUG] 3ffffda0: 3fff710c 00000001 3fff07b4 40217b83 
[DEBUG] 3ffffdb0: 3fff3714 00000910 00000910 4010020c 
[DEBUG] 3ffffdc0: 00000001 3fff710c 3ffffe10 4010068c 
[DEBUG] 3ffffdd0: 3ffea6f0 50590f0a 3ffffe10 4022cb94 
[DEBUG] 3ffffde0: 3fff2274 00000a2f 00000a2f 4010020c 
[DEBUG] 3ffffdf0: 00000001 00000000 3ffffe40 3fff7bf4 
[DEBUG] 3ffffe00: 00000001 3fff710c 00000000 4022d47a 
[DEBUG] 3ffffe10: 3fff72e4 3ffe85e4 40221648 4022df4d 
[DEBUG] 3ffffe20: 00000000 31343033 3fff710c 4021fd4d 
[DEBUG] 3ffffe30: 3fff2274 00000000 3fff710c 40220636 
[DEBUG] 3ffffe40: 3fff710c 3ffe85e4 4021faa0 4022119c 
[DEBUG] 3ffffe50: 3fff755c 000000d8 3fff731c 401004d8 
[DEBUG] 3ffffe60: 3fff2274 00000906 00000906 3fff2860 
[DEBUG] 3ffffe70: 00000104 000000d8 3fff731c 4022066d 
[DEBUG] 3ffffe80: 3fff7bf4 caa5a253 00002200 401075b0 
[DEBUG] 3ffffe90: 3fff7294 3fff286c 3fff7bf4 4022dfac 
[DEBUG] 3ffffea0: 3fff7bf4 00000104 3fff755c 402217a5 
[DEBUG] 3ffffeb0: 00000001 3fff2a58 3fff755c 4021a228 
[DEBUG] 3ffffec0: 3fff7744 3fff2868 3fff2864 4021a248 
[DEBUG] 3ffffed0: 3fff7744 3fff2868 3fff2864 40243505 
[DEBUG] 3ffffee0: 00000000 9e590f0a 00000010 00000000 
[DEBUG] 3ffffef0: 00000010 00000000 3fff1154 401075a0 
[DEBUG] 3fffff00: 40230000 00000000 00000064 3fff2a50 
[DEBUG] 3fffff10: 3ffebe5a 3fff2a58 3fff6cc4 40241a55 
[DEBUG] 3fffff20: 3fff27bc 3fff650c 3fff650c 3ffeff60 
[DEBUG] 3fffff30: 00000000 3fff6cc4 0000001c 3fff650c 
[DEBUG] 3fffff40: 3ffebe4c 00000000 3fff6cc4 40240e4d 
[DEBUG] 3fffff50: 50590f0a 0000005e 00000000 00000044 
[DEBUG] 3fffff60: 00000002 0000001a 4023063b 3ffee978 
[DEBUG] 3fffff70: 3ffebe24 3fffdcc0 3ffeaff8 3ffeaff8 
[DEBUG] 3fffff80: 402305ae 3ffee978 00000000 3fff657c 
[DEBUG] 3fffff90: 3fffdc80 00000000 3fff6cc4 40238acb 
[DEBUG] 3fffffa0: 40000f49 3fffdab0 3fffdab0 40000f49 
[DEBUG] <<<stack<<<
[039652] +OK

_Originally posted by @Interpyme in https://github.com/xoseperez/espurna/issues/1617#issuecomment-489311595_

### PR DESCRIPTION
**Pull request by mcspr**
Resolve #1731 (?), #1823 (original question), #1824, #1831 
cc @gernst48 @tonilopezmr @Interpyme @ruimarinho 

I'll clean it up later from some experimental leftovers and fix some dumb behaviour (like, not immediately sending sensor readouts)
POW runs this reasonably well. Refresh does not crash 🤷‍♂
(but I could not make it crash even with old builds. must be something related to OS / browser / network conditions)

And probably try again to rethink how to push static data before everything else, to reduce total number of messages (although, it is smaller than before #1387 / 1.13.3)

Keeping ArduinoJson 5 for now.

### CODE REVIEW

**Comment by mcspr** [comment]
If anyone can test the tree itself (i.e. checkout the mcspr:web/fixed-size-json-v5), that would be greatly appreciated.


Some notes about the ws module, as the main changes are there... The goal is to chain send_callback_f funcs so that it firstly bulks up some known constants in a single object root and sends it (...Visible is an obvious one, since it only depends on the module being present). But, after that, callbacks need to be called separately again. Some state / stage var can control this, maybe... And the final one sending sensor data.

**Comment by tonilopezmr** [comment]
wow!! I didn't see it, I'm going to test it right now!

**Comment by tonilopezmr** [comment]
This PR fixes my problems!!

**Comment by tonilopezmr** [comment]
I'm still facing this #1731 because I don't get `current`, `Apparent power` and `Reactive Power`

**Comment by mcspr** [comment]
Great. Need to also check Windows / Chrome situation, if queuing does work properly with delayed acks (...and the main reason single big json was used in the first place)

OT: I think we determined in the #1822 that indexing in the hwl sensor needs to be customizable, nothing in the web specifically. That way, it will also not be there in mqtt reports, thingspeak etc. And I kind of missed whether you wanted to add that yourself or not 🤔

**Comment by tonilopezmr** [comment]
I tested it using mac os and chrome

**Comment by mcspr** [comment]
*Note-to-self:*
`std::queue<T>`, where `T` was never seen before, adds ~500bytes to the total firmware size (...because there is also `std::deque<T>` inside of it?)
One alternative is to use custom linked list class.
*or* `LinkedList<T>` from ESPAsyncWebserver, which is exported by default -> https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/StringArray.h
not as big, surprisingly. API is almost the same: empty() -> isEmpty(), pop() -> remove(front()), push() -> add()

**Comment by mcspr** [comment]
Resolves #1824 
Resolves #1831

**Comment by tonilopezmr** [comment]
Congratulations @mcspr, awesome PR!!

**Comment by ruimarinho** [comment]
@mcspr does this solve the double authentication request for credentials on Safari?

**Comment by mcspr** [comment]
@ruimarinho nothing about the auth was changed here. do you mean that it is showing auth pop-up twice?
`/` is requesting digest auth and then script inside is calling `/auth`, also requiring digest auth. if yes, safari is an odd one here :/ every other browser caches credentials after the first request

**Comment by ruimarinho** [comment]
@mcspr indeed, that. For some reason I made the connection between the WS connection and the double digest auth, but I haven't looked at the code yet. Maybe we can remove the script call to /auth and just depend on session cookie to pass on the auth header?

**Comment by mcspr** [comment]
Probably, yes. It is pretty basic right now, `/auth` whole purpose is to set / update {IP: timeout} in the internal "ticket" table. WS handler then checks that table, since Safari also does not support digest auth for Upgrade protocols (https://github.com/xoseperez/espurna/issues/507#issuecomment-372827255).
Every request is filtered via `webAuthenticate(request)` and depends on the result of `request->authenticate(WEB_USERNAME, password);` where it checks if browser used digest auth headers or not. It is a likely place to move current auth mechanism "ticket" update, or update it with some per-client session instead

**Pull request merged**
